version: '3.8'

services:

  api:
    build: ./api
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  front:
    build: ./front
    restart: always

  database:
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - ./.env 
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - front
    restart: always

volumes:
  pgdata:
