version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db
    env_file:
      - ./.env

    restart: on-failure
    command: 
      npm run dev

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - ./.env 
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
